### ISSUE TITLE
[Bug]: JEI recipe's disappear after updating mod 

### ISSUE THREAD

**Issue by VillainVibe** [TheIllusiveC4/VeinMining#125]
### Minecraft Version

1.20.1

### What happened?

After installing the latest update alot of the jei recipes from my other mods disappeared.
Downgrading resolved the issue. 

### How do you trigger this bug?

Update Veinmining

### Loader

NeoForge

### Loader Version

47.1.105

### Mod Version

1.4.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, as installing the latest update seems to make JEI appear as normal.

1. Can you share your `latest.log` file?
2. Which recipes and from which mods disappear when you notice this issue?

**Comment by VillainVibe** [comment]
I'll update the mod and give the latest.log
From what I have noticed the recipes from the create mod where partially missing.

**Comment by VillainVibe** [comment]
Very weird, for some reason its not missing any recipes now, it sure was before and downgrading the mod solved the problem
I even restarted my client and server a couple of times to make sure.

Anyways I'll give my latest.log with the update installed just in case.

[latest.log](https://github.com/illusivesoulworks/veinmining/files/15179425/latest.log)

**Comment by TheIllusiveC4** [comment]
There's nothing suspicious in the log file. If it's resolved now, I suspect that it was caused by another problem from another mod showing up (potentially Create, since it was those recipes that were missing). The difference between 1.4.0 and 1.4.1 is a single line of code and it would not affect recipes in JEI, so I don't believe it was an issue coming from this mod.

**Comment by VillainVibe** [comment]
Yeah I'm also suspecting its related to a other mod, since the bug persists after downgrading to. 
The recipe disappearance it resolved. 
It must have bin a coincidence while it updated you're mod. 
My apologies, Thank you for you're time
